// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxc7uuufT_WTPyepAGdzn-ydmRGzoMfw',
    appId: '1:934794879369:web:f159d64e47258021268158',
    messagingSenderId: '934794879369',
    projectId: 'medicare-69a58',
    authDomain: 'medicare-69a58.firebaseapp.com',
    storageBucket: 'medicare-69a58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_KIT7KD4A_2M7oaBcOQAJAHxH_9gDto',
    appId: '1:934794879369:android:b975b9b739b9fb56268158',
    messagingSenderId: '934794879369',
    projectId: 'medicare-69a58',
    storageBucket: 'medicare-69a58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2fKmCAAFWE7Eg793Nx0amHKFNKp3OOs',
    appId: '1:934794879369:ios:c81604c26ff354b3268158',
    messagingSenderId: '934794879369',
    projectId: 'medicare-69a58',
    storageBucket: 'medicare-69a58.firebasestorage.app',
    androidClientId: '934794879369-kagnd5ij4goe7kjt2pk3neq50mf7ks69.apps.googleusercontent.com',
    iosClientId: '934794879369-hjfnp0krf6fo05b5vehh1bgr6e5jasi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqxc7uuufT_WTPyepAGdzn-ydmRGzoMfw',
    appId: '1:934794879369:web:1a8fe9f730986e27268158',
    messagingSenderId: '934794879369',
    projectId: 'medicare-69a58',
    authDomain: 'medicare-69a58.firebaseapp.com',
    storageBucket: 'medicare-69a58.firebasestorage.app',
  );

}